using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Maps.NET.Static
{
    class Place
    {
        public Place(string Name, string Color, string Image) { this.Name = Name; this.Color = Color; this.Image = Image; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Image { get; set; }
    }
    class StaticPlaces
    {
        public static List<Place> listPlaces = new List<Place>()
            {
                new Place("accounting","#FF0000","/Assets/Places/Types/Accounting.png"),
                new Place("airport","#00FF00","/Assets/Places/Types/Airport.png"),
                new Place("amusement park","#0000FF","/Assets/Places/Types/Amusement_park.png"),
                new Place("aquarium","#FF00FF","/Assets/Places/Types/Aquarium.png"),
                new Place("art gallery","#FFAA00","/Assets/Places/Types/Art_gallery.png"),
                new Place("atm","#00AAFF","/Assets/Places/Types/Atm.png"),
                new Place("bakery","#000000","/Assets/Places/Types/Bakery.png"),
                new Place("bank","#FF0000","/Assets/Places/Types/Bank.png"),
                new Place("bar","#00FF00","/Assets/Places/Types/Bar.png"),
                new Place("beauty salon","#0000FF","/Assets/Places/Types/Beauty_salon.png"),
                new Place("bicycle store","#FF00FF","/Assets/Places/Types/Bicycle_store.png"),
                new Place("book store","#FFAA00","/Assets/Places/Types/Book_store.png"),
                new Place("bowling alley","#00AAFF","/Assets/Places/Types/Bowling_alley.png"),
                new Place("bus station","#000000","/Assets/Places/Types/Bus_station.png"),
                new Place("cafe","#FF0000","/Assets/Places/Types/Cafe.png"),
                new Place("campground","#00FF00","/Assets/Places/Types/Campground.png"),
                new Place("car dealer","#0000FF","/Assets/Places/Types/Car_dealer.png"),
                new Place("car rental","#FF00FF","/Assets/Places/Types/Car_rental.png"),
                new Place("car repair","#FFAA00","/Assets/Places/Types/Car_repair.png"),
                new Place("car wash","#00AAFF","/Assets/Places/Types/Car_wash.png"),
                new Place("casino","#000000","/Assets/Places/Types/Casino.png"),
                new Place("cemetery","#FF0000","/Assets/Places/Types/Cemetery.png"),
                new Place("church","#00FF00","/Assets/Places/Types/Church.png"),
                new Place("city hall","#0000FF","/Assets/Places/Types/City_hall.png"),
                new Place("clothing store","#FF00FF","/Assets/Places/Types/Clothing_store.png"),
                new Place("convenience store","#FFAA00","/Assets/Places/Types/Convenience_store.png"),
                new Place("courthouse","#00AAFF","/Assets/Places/Types/Courthouse.png"),
                new Place("dentist","#000000","/Assets/Places/Types/Dentist.png"),
                new Place("department store","#FF0000","/Assets/Places/Types/Department_store.png"),
                new Place("doctor","#00FF00","/Assets/Places/Types/Doctor.png"),
                new Place("electrician","#0000FF","/Assets/Places/Types/Electrician.png"),
                new Place("electronics store","#FF00FF","/Assets/Places/Types/Electronics_store.png"),
                new Place("embassy","#FFAA00","/Assets/Places/Types/Embassy.png"),
                new Place("establishment","#00AAFF","/Assets/Places/Types/Establishment.png"),
                new Place("finance","#000000","/Assets/Places/Types/Finance.png"),
                new Place("fire station","#FF0000","/Assets/Places/Types/Fire_station.png"),
                new Place("florist","#00FF00","/Assets/Places/Types/Florist.png"),
                new Place("food","#0000FF","/Assets/Places/Types/Food.png"),
                new Place("funeral home","#FF00FF","/Assets/Places/Types/Funeral_home.png"),
                new Place("furniture store","#FFAA00","/Assets/Places/Types/Furniture_store.png"),
                new Place("gas station","#00AAFF","/Assets/Places/Types/Gas_station.png"),
                new Place("general contractor","#000000","/Assets/Places/Types/General_contractor.png"),
                new Place("grocery or supermarket","#FF0000","/Assets/Places/Types/Grocery_or_supermarket.png"),
                new Place("gym","#00FF00","/Assets/Places/Types/Gym.png"),
                new Place("hair care","#0000FF","/Assets/Places/Types/Hair_care.png"),
                new Place("hardware store","#FF00FF","/Assets/Places/Types/Hardware_store.png"),
                new Place("health","#FFAA00","/Assets/Places/Types/Health.png"),
                new Place("hindu temple","#FF0000","/Assets/Places/Types/Hindu_temple.png"),
                new Place("home goods store","#00FF00","/Assets/Places/Types/Home_goods_store.png"),
                new Place("hospital","#0000FF","/Assets/Places/Types/Hospital.png"),
                new Place("insurance agency","#FF00FF","/Assets/Places/Types/Insurance_agency.png"),
                new Place("jewelry store","#FFAA00","/Assets/Places/Types/Jewelry_store.png"),
                new Place("laundry","#00AAFF","/Assets/Places/Types/Laundry.png"),
                new Place("lawyer","#000000","/Assets/Places/Types/Lawyer.png"),
                new Place("library","#FF0000","/Assets/Places/Types/Library.png"),
                new Place("liquor store","#00FF00","/Assets/Places/Types/Liquor_store.png"),
                new Place("courthouse","#0000FF","/Assets/Places/Types/Courthouse.png"),
                new Place("local government office","#FF00FF","/Assets/Places/Types/Local_government_office.png"),
                new Place("locksmith","#FFAA00","/Assets/Places/Types/Locksmith.png"),
                new Place("lodging","#00AAFF","/Assets/Places/Types/Lodging.png"),
                new Place("all","#000000","/Assets/Places/Types/Man.png"),
                new Place("meal delivery","#FF0000","/Assets/Places/Types/Meal_delivery.png"),
                new Place("meal takeaway","#00FF00","/Assets/Places/Types/Meal_takeaway.png"),
                new Place("mosque","#0000FF","/Assets/Places/Types/Mosque.png"),
                new Place("movie rental","#FF00FF","/Assets/Places/Types/Movie_rental.png"),
                new Place("movie theater","#FFAA00","/Assets/Places/Types/Movie_theater.png"),
                new Place("moving company","#00AAFF","/Assets/Places/Types/Moving_company.png"),
                new Place("museum","#000000","/Assets/Places/Types/Museum.png"),
                new Place("night club","#FF0000","/Assets/Places/Types/Night_club.png"),
                new Place("painter","#00FF00","/Assets/Places/Types/Painter.png"),
                new Place("park","#0000FF","/Assets/Places/Types/Park.png"),
                new Place("parking","#FF00FF","/Assets/Places/Types/Parking.png"),
                new Place("pet store","#FFAA00","/Assets/Places/Types/Pet_store.png"),
                new Place("pharmacy","#00AAFF","/Assets/Places/Types/Pharmacy.png"),
                new Place("physiotherapist","#000000","/Assets/Places/Types/Physiotherapist.png"),
                new Place("place of worship","#FF0000","/Assets/Places/Types/Place_of_worship.png"),
                new Place("plumber","#00FF00","/Assets/Places/Types/Plumber.png"),
                new Place("Police","#0000FF","/Assets/Places/Types/Police.png"),
                new Place("post office","#FF00FF","/Assets/Places/Types/Post_office.png"),
                new Place("real estate agency","#FFAA00","/Assets/Places/Types/Real_estate_agency.png"),
                new Place("restaurant","#00AAFF","/Assets/Places/Types/Restaurant.png"),
                new Place("roofing contractor","#000000","/Assets/Places/Types/Roofing_contractor.png"),
                new Place("rv park","#FF0000","/Assets/Places/Types/Rv_park.png"),
                new Place("school","#00FF00","/Assets/Places/Types/School.png"),
                new Place("shoe store","#0000FF","/Assets/Places/Types/Shoe_store.png"),
                new Place("shopping mall","#FF00FF","/Assets/Places/Types/Shopping_mall.png"),
                new Place("spa","#FFAA00","/Assets/Places/Types/Spa.png"),
                new Place("stadium","#00AAFF","/Assets/Places/Types/Stadium.png"),
                new Place("storage","#000000","/Assets/Places/Types/Storage.png"),
                new Place("store","#FF0000","/Assets/Places/Types/Store.png"),
                new Place("subway station","#00FF00","/Assets/Places/Types/Subway_station.png"),
                new Place("synagogue","#0000FF","/Assets/Places/Types/Synagogue.png"),
                new Place("taxi stand","#FF00FF","/Assets/Places/Types/Taxi_stand.png"),
                new Place("train station","#FFAA00","/Assets/Places/Types/Train_station.png"),
                new Place("travel agency","#00AAFF","/Assets/Places/Types/Travel_agency.png"),
                new Place("university","#000000","/Assets/Places/Types/University.png"),
                new Place("veterinary care","#FF0000","/Assets/Places/Types/Veterinary_care.png"),
                new Place("zoo","#00FF00","/Assets/Places/Types/Zoo.png"),
            };
    }
}
